SRC=		2048.PAS
UNITS=		ADDTILE.PAS GRAPHICS.PAS GRID.PAS KEYMAP.PAS MESSAGES.PAS MOTION.PAS STAGES.PAS STATE.PAS
BIN=		2048
COMPILER=	fpc
CFLAGS=		-Mtp

${BIN}: ${SRC} ${UNITS}
	${COMPILER} ${CFLAGS} ${SRC}

clean:
	rm -f ${BIN} *.o *.ppu *.tpu
